name: generate snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Swih
          outputs: |
            dist/snake.svg?color_snake=%23fff9e0&color_dots=%23222222,%23663300,%23a05010,%23ff9500,%23ffcc00

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
